carbonara: log a message and do not fail if a file is missing
When rewriting data for compression, it's possible a file
<metric>_<splitkey>_<aggregation_method>_<granularity> is missing,
because of some data corruption. In that case the following traceback happens:

  Traceback (most recent call last):
    File "/usr/lib/python2.7/site-packages/gnocchi/storage/_carbonara.py", line 557, in process_new_measures
      ignore_too_old_timestamps=True)
    File "/usr/lib/python2.7/site-packages/gnocchi/carbonara.py", line 217, in set_values
      before_truncate_callback(self)
    File "/usr/lib/python2.7/site-packages/gnocchi/storage/_carbonara.py", line 551, in _map_add_measures
      for aggregation in agg_methods))
    File "/usr/lib/python2.7/site-packages/gnocchi/storage/_carbonara.py", line 675, in _map_no_thread
      return list(itertools.starmap(method, list_of_args))
    File "/usr/lib/python2.7/site-packages/gnocchi/storage/_carbonara.py", line 316, in _add_measures
      oldest_mutable_timestamp)
    File "/usr/lib/python2.7/site-packages/gnocchi/storage/_carbonara.py", line 249, in _store_timeserie_split
      offset, data = split.serialize(key, compressed=write_full)
  AttributeError: 'NoneType' object has no attribute 'serialize'

This patch makes the driver log a warning and return, so it just ignores
the failure and continues anyway.

Change-Id: I4f367b2418c8be0067746c88bcce74ca756acf4e