Pin oslo.db<=4.13.0
oslo.db==4.13.1 introduced some changes causing the tests to fail

File "/xxx/lib/python2.7/site-packages/oslo_db/sqlalchemy/utils.py",
 line 77, in _get_unique_keys
    info = model.__table__.info
AttributeError: type object 'Result' has no attribute '__table__'

Seems to be introduced in:
https://github.com/openstack/oslo.db/blame/4.13.1/oslo_db/sqlalchemy/utils.py#L77

Change-Id: I679a958e7b95f594118c2061fa19469ba6ef59dd